version: 2
updates:
  # Enable version updates for npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json, etc.
    schedule:
      interval: "dayly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your GitHub Actions definitions
    schedule:
      interval: "dayly"
